export const movieList = {
  movieList: [
    {
      adult: false,
      backdrop_path: '/ziTxBaF1AhbUwcv2IBiFJAf54qD.jpg',
      id: 65086,
      overview: 'The story follows a young lawyer, Arthur Kipps.',
      popularity: 16.334,
      poster_path: '/aJbeDPUwDe9MLpseTFrNTBaQPzf.jpg',
      release_date: '2012-02-03',
      title: 'The Woman in Black',
      vote_average: 6.11,
    },
    {
      adult: false,
      id: 102899,
      overview: 'Armed with the astonishing ability to shrink in scale but increase in strength.',
      popularity: 69.704,
      poster_path: '/rS97hUJ1otKTTripGwQ0ujbuIri.jpg',
      release_date: '2015-07-14',
      title: 'Ant-Man',
      vote_average: 7.088,
    },
  ],
  title: 'test',
};

export const navigation = { navigate: jest.fn(), getParam: jest.fn(), setOptions: jest.fn() };

export const longList = [
  {
    movieList: [
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [Array],
        id: 878875,
        original_language: 'es',
        original_title: 'Extensión cultural',
        overview: 'Documentary short film commissioned by the SEP. Plot unknown.',
        popularity: 0.6,
        poster_path: '/b3sD3hDBBzMSDfCKviEuXKXjCvv.jpg',
        release_date: '2075-01-01',
        title: 'Cultural Extension',
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [Array],
        id: 878873,
        original_language: 'es',
        original_title: 'Sur: sureste 2604',
        overview:
          'In the future, a couple hides from their pursuers in the archaeological ruins of Tulúm, on the beaches of Cozumel, and in the hubbub of a day out in an indigenous town.',
        popularity: 0.6,
        poster_path: '/b3sD3hDBBzMSDfCKviEuXKXjCvv.jpg',
        release_date: '2074-01-01',
        title: 'South: Southeast 2604',
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: '/1JwzQ4Luw5KH3l2Lm6p84ab3TiP.jpg',
        genre_ids: [Array],
        id: 11165,
        original_language: 'en',
        original_title: 'Tora! Tora! Tora!',
        overview:
          'In the summer of 1941, the United States and Japan seem on the brink of war after constant embargos and failed diplomacy come to no end. "Tora! Tora! Tora!", named after the code words use by the lead Japanese pilot to indicate they had surprised the Americans, covers the days leading up to the attack on Pearl Harbor, which plunged America into the Second World War.',
        popularity: 11.198,
        poster_path: '/c311sN931DixuZRer0JGYCwpx9N.jpg',
        release_date: '1970-01-26',
        title: 'Tora! Tora! Tora!',
        video: false,
        vote_average: 7.1,
        vote_count: 362,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [Array],
        id: 863797,
        original_language: 'es',
        original_title: 'Quiero estudiar',
        overview: '',
        popularity: 0.843,
        poster_path: null,
        release_date: '2050-12-30',
        title: 'Quiero estudiar',
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [Array],
        id: 857132,
        original_language: 'zh',
        original_title: '我不是李小龙',
        overview: '',
        popularity: 0.6,
        poster_path: null,
        release_date: '2049-01-01',
        title: '我不是李小龙',
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [Array],
        id: 855924,
        original_language: 'zh',
        original_title: '君子道：上海滩后传',
        overview: '',
        popularity: 0.6,
        poster_path: '/y1GiMJ6l5izZcenQA3hC5RcQY6p.jpg',
        release_date: '2030-01-01',
        title: '君子道：上海滩后传',
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [Array],
        id: 837362,
        original_language: 'en',
        original_title: 'Melinda Hill: Inappropriate',
        overview:
          'Melinda Hill uses laughter as medicine in this comedy special about moving from trauma bonding to trauma mending. Imparting insights and crushing confessions punctuated by punchlines in a soul-baring storytelling style, she reflects on transformation, transcendence and triumph of the human spirit. Inappropriate is its own genre where healing meets comedy; it’s heal-arious.',
        popularity: 1.178,
        poster_path: '/c6nfNoq98VaIYUYXRA6nEjNSwxt.jpg',
        release_date: '2029-10-20',
        title: 'Melinda Hill: Inappropriate',
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: '/sEcmbz4uNlHwVAvFGmAsgAdRDkD.jpg',
        genre_ids: [Array],
        id: 566220,
        original_language: 'en',
        original_title: 'Shooting the Mafia',
        overview:
          'Sicilian photojournalist Letizia Battaglia began a long battle against the ruthless Cosa Nostra when she first photographed the sinister scene of a brutal murder. Documenting the barbaric rule of the Italian Mafia, she was an unwavering witness to its crimes. His art and courage helped end the horrific and bloody reign of the Corleonesi clan.',
        popularity: 2.905,
        poster_path: '/zVMUGzZDAWkLGqBw5APQNB0F4Uw.jpg',
        release_date: '2019-11-22',
        title: 'Shooting the Mafia',
        video: false,
        vote_average: 7,
        vote_count: 14,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [Array],
        id: 393209,
        original_language: 'en',
        original_title: 'Avatar 5',
        overview: '',
        popularity: 23.939,
        poster_path: '/qeAknsrFRHRvjIq2HrlBsmYy2KL.jpg',
        release_date: '2028-12-20',
        title: 'Avatar 5',
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: '/pIp5lY8ikwTelMsL1snfQQhdZ1j.jpg',
        genre_ids: [Array],
        id: 678392,
        original_language: 'de',
        original_title: 'Egon Schiele',
        overview:
          'An account of the short life and the astonishing and provocative work of the Austrian painter Egon Schiele (1890-1918), seen through the peculiar point of view and the critic voices of the women who defined the paramount milestones of his existence: Gerti, his sister; Wally, his main model and lover; and Edith, his wife. A brief story of love, hate, betrayal and misfortune.',
        popularity: 0.6,
        poster_path: '/gkeLMOW6u35eXJTAnlmFxKa9fQH.jpg',
        release_date: '2018-11-04',
        title: 'Egon Schiele: Between Love and Hate',
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
    ],
    title: 'Recently Added',
  },
  {
    movieList: [
      {
        adult: false,
        backdrop_path: '/gNBCvtYyGPbjPCT1k3MvJuNuXR6.jpg',
        genre_ids: [Array],
        id: 19404,
        original_language: 'hi',
        original_title: 'दिलवाले दुल्हनिया ले जायेंगे',
        overview:
          'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
        popularity: 31.128,
        poster_path: '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
        release_date: '1995-10-20',
        title: 'Dilwale Dulhania Le Jayenge',
        video: false,
        vote_average: 8.8,
        vote_count: 3148,
      },
      {
        adult: false,
        backdrop_path: '/9Xw0I5RV2ZqNLpul6lXKoviYg55.jpg',
        genre_ids: [Array],
        id: 278,
        original_language: 'en',
        original_title: 'The Shawshank Redemption',
        overview:
          'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
        popularity: 87.704,
        poster_path: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        release_date: '1994-09-23',
        title: 'The Shawshank Redemption',
        video: false,
        vote_average: 8.7,
        vote_count: 19769,
      },
      {
        adult: false,
        backdrop_path: '/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
        genre_ids: [Array],
        id: 238,
        original_language: 'en',
        original_title: 'The Godfather',
        overview:
          'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
        popularity: 72.068,
        poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
        release_date: '1972-03-14',
        title: 'The Godfather',
        video: false,
        vote_average: 8.7,
        vote_count: 14832,
      },
      {
        adult: false,
        backdrop_path: '/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg',
        genre_ids: [Array],
        id: 724089,
        original_language: 'en',
        original_title: "Gabriel's Inferno Part II",
        overview:
          "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
        popularity: 11.844,
        poster_path: '/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg',
        release_date: '2020-07-31',
        title: "Gabriel's Inferno Part II",
        video: false,
        vote_average: 8.7,
        vote_count: 1308,
      },
      {
        adult: false,
        backdrop_path: '/1EAxNqdkVnp48a7NUuNBHGflowM.jpg',
        genre_ids: [Array],
        id: 283566,
        original_language: 'ja',
        original_title: 'シン・エヴァンゲリオン劇場版:||',
        overview:
          'In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.',
        popularity: 209.788,
        poster_path: '/jDwZavHo99JtGsCyRzp4epeeBHx.jpg',
        release_date: '2021-03-08',
        title: 'Evangelion: 3.0+1.0 Thrice Upon a Time',
        video: false,
        vote_average: 8.7,
        vote_count: 320,
      },
      {
        adult: false,
        backdrop_path: '/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg',
        genre_ids: [Array],
        id: 761053,
        original_language: 'en',
        original_title: "Gabriel's Inferno Part III",
        overview:
          "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
        popularity: 30.026,
        poster_path: '/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg',
        release_date: '2020-11-19',
        title: "Gabriel's Inferno Part III",
        video: false,
        vote_average: 8.6,
        vote_count: 875,
      },
      {
        adult: false,
        backdrop_path: '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
        genre_ids: [Array],
        id: 696374,
        original_language: 'en',
        original_title: "Gabriel's Inferno",
        overview:
          "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
        popularity: 10.573,
        poster_path: '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
        release_date: '2020-05-29',
        title: "Gabriel's Inferno",
        video: false,
        vote_average: 8.6,
        vote_count: 2116,
      },
      {
        adult: false,
        backdrop_path: '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
        genre_ids: [Array],
        id: 424,
        original_language: 'en',
        original_title: "Schindler's List",
        overview:
          'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
        popularity: 40.077,
        poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
        release_date: '1993-11-30',
        title: "Schindler's List",
        video: false,
        vote_average: 8.6,
        vote_count: 11846,
      },
      {
        adult: false,
        backdrop_path: '/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg',
        genre_ids: [Array],
        id: 240,
        original_language: 'en',
        original_title: 'The Godfather: Part II',
        overview:
          'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
        popularity: 44.03,
        poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
        release_date: '1974-12-20',
        title: 'The Godfather: Part II',
        video: false,
        vote_average: 8.6,
        vote_count: 8902,
      },
      {
        adult: false,
        backdrop_path: '/u1wHUA0R48FH4WV3sGqjwx3aNZm.jpg',
        genre_ids: [Array],
        id: 632632,
        original_language: 'ja',
        original_title: '映画 ギヴン',
        overview:
          "The film centers on the love relationship among the band's bassist Haruki Nakayama, drummer Akihiko Kaji, and Akihiko's roommate and ex-boyfriend Ugetsu Murata.",
        popularity: 119.547,
        poster_path: '/xKCtoYHUyX8zAg68eemnYa2orep.jpg',
        release_date: '2020-08-22',
        title: 'Given',
        video: false,
        vote_average: 8.6,
        vote_count: 251,
      },
    ],
    title: 'Trending Now',
  },
];

export const similarMoviesResults = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/qusjc74SWvno7g8EeHww3UVfzZp.jpg',
      genre_ids: [Array],
      id: 11596,
      original_language: 'en',
      original_title: 'New Nightmare',
      overview:
        "As Heather Langenkamp considers making another Nightmare on Elm Street film with Wes Craven, her son, Dylan, falls under the spell of the iconic disfigured villain Freddy Krueger. Eventually, Langenkamp must confront Freddy's demonic spirit to save the soul of Dylan.",
      popularity: 25.264,
      poster_path: '/eN3UZUYapJ2CJCD9dN0LUZLouKa.jpg',
      release_date: '1994-10-13',
      title: 'New Nightmare',
      video: false,
      vote_average: 6.459,
      vote_count: 936,
    },
    {
      adult: false,
      backdrop_path: '/iXlHfi9hq7nfSv31pBab8fpMfZh.jpg',
      genre_ids: [Array],
      id: 10830,
      original_language: 'en',
      original_title: 'Matilda',
      overview:
        'An extraordinarily intelligent young girl from a cruel and uncaring family discovers she possesses telekinetic powers and is sent off to a school headed by a tyrannical principal.',
      popularity: 25.674,
      poster_path: '/wnLbqoGRGdnPNjMV6rY75wgRamd.jpg',
      release_date: '1996-08-02',
      title: 'Matilda',
      video: false,
      vote_average: 7.112,
      vote_count: 3273,
    },
    {
      adult: false,
      backdrop_path: '/d59cyYhl5xx4x4KQCY9JkwU8xRy.jpg',
      genre_ids: [Array],
      id: 10228,
      original_language: 'ja',
      original_title: '劇場版ポケットモンスター ミュウツーの逆襲',
      overview:
        "The adventure explodes into action with the debut of Mewtwo, a bio-engineered Pokémon created from the DNA of Mew, the rarest of all Pokémon. Determined to prove its superiority, Mewtwo lures Satoshi, Pikachu and others into a Pokémon match like none before. Mewtwo vs. Mew. Super-clones vs. Pokémon. It's the ultimate showdown ... with the very future of the world at stake!",
      popularity: 19.568,
      poster_path: '/3m1kyUksL3vf4anbYMbLUWXTb3W.jpg',
      release_date: '1998-07-18',
      title: 'Pokémon: The First Movie - Mewtwo Strikes Back',
      video: false,
      vote_average: 6.897,
      vote_count: 1074,
    },
    {
      adult: false,
      backdrop_path: '/anOL7qSqbxv9G6xmAsYr3UR10Ds.jpg',
      genre_ids: [Array],
      id: 10229,
      original_language: 'en',
      original_title: 'A Walk to Remember',
      overview:
        'When the popular, restless Landon Carter is forced to participate in the school drama production he falls in love with Jamie Sullivan, the daughter of the town\'s minister. Jamie has a "to-do" list for her life and also a very big secret she must keep from Landon.',
      popularity: 40.175,
      poster_path: '/8lUYMvWdHA0Q0k5F76RQCeCBUkA.jpg',
      release_date: '2002-01-25',
      title: 'A Walk to Remember',
      video: false,
      vote_average: 7.735,
      vote_count: 3338,
    },
    {
      adult: false,
      backdrop_path: '/eMzBeFVxYS63O7lf1S2QYUJRB3Z.jpg',
      genre_ids: [Array],
      id: 10131,
      original_language: 'en',
      original_title: 'A Nightmare on Elm Street 4: The Dream Master',
      overview:
        'Dream demon Freddy Krueger is resurrected from his apparent demise, and rapidly tracks down and kills the remainder of the Elm Street kids. However, Kristen, who can draw others into her dreams, wills her special ability to her friend Alice. Alice soon realizes that Freddy is taking advantage of that unknown power to pull a new group of children into his foul domain.',
      popularity: 22.543,
      poster_path: '/boStYG7jKdoIZTduiOOsUVknD13.jpg',
      release_date: '1988-08-19',
      title: 'A Nightmare on Elm Street 4: The Dream Master',
      video: false,
      vote_average: 5.844,
      vote_count: 930,
    },
    {
      adult: false,
      backdrop_path: '/mXBDQ9n2osF0BqBjXY9JDyadyRb.jpg',
      genre_ids: [Array],
      id: 9339,
      original_language: 'en',
      original_title: 'Click',
      overview:
        "A married workaholic, Michael Newman doesn't have time for his wife and children, not if he's to impress his ungrateful boss and earn a well-deserved promotion. So when he meets Morty, a loopy sales clerk, he gets the answer to his prayers: a magical remote that allows him to bypass life's little distractions with increasingly hysterical results.",
      popularity: 21.16,
      poster_path: '/x7rM5dwQefvpXqHKQs4TrpoRyz3.jpg',
      release_date: '2006-06-23',
      title: 'Click',
      video: false,
      vote_average: 6.215,
      vote_count: 5528,
    },
    {
      adult: false,
      backdrop_path: '/x30bpi16AFWrfGVhYMqujbcCAWS.jpg',
      genre_ids: [Array],
      id: 9378,
      original_language: 'en',
      original_title: 'Thir13en Ghosts',
      overview:
        'Arthur and his two children, Kathy and Bobby, inherit his Uncle Cyrus\'s estate: a glass house that serves as a prison to 12 ghosts. When the family, accompanied by Bobby\'s Nanny and an attorney, enter the house they find themselves trapped inside an evil machine "designed by the devil and powered by the dead" to open the Eye of Hell. Aided by Dennis, a ghost hunter, and his rival Kalina, a ghost rights activist out to set the ghosts free, the group must do what they can to get out of the house alive.',
      popularity: 37.908,
      poster_path: '/j4UNVqRy1SqBjaf3f1uEBMuCgwb.jpg',
      release_date: '2001-10-26',
      title: 'Thir13en Ghosts',
      video: false,
      vote_average: 6.164,
      vote_count: 1472,
    },
    {
      adult: false,
      backdrop_path: '/i4m14DMv0JG4AOH6sP7Pes87A9x.jpg',
      genre_ids: [Array],
      id: 11104,
      original_language: 'cn',
      original_title: '重慶森林',
      overview:
        'Two melancholic Hong Kong policemen fall in love: one with a mysterious underworld figure, the other with a beautiful and ethereal server at a late-night restaurant he frequents.',
      popularity: 13.425,
      poster_path: '/43I9DcNoCzpyzK8JCkJYpHqHqGG.jpg',
      release_date: '1994-07-14',
      title: 'Chungking Express',
      video: false,
      vote_average: 8.052,
      vote_count: 985,
    },
    {
      adult: false,
      backdrop_path: '/8v5z3Wa6GbyjqvMxXz11PTmDCwS.jpg',
      genre_ids: [Array],
      id: 9495,
      original_language: 'en',
      original_title: 'The Crow',
      overview:
        'Exactly one year after young rock guitarist Eric Draven and his fiancée are brutally killed by a ruthless gang of criminals, Draven—watched over by a hypnotic crow—returns from the grave to exact revenge.',
      popularity: 23.724,
      poster_path: '/wF2Tnf0bdYrzCKVbWh0mFwPJS6k.jpg',
      release_date: '1994-05-11',
      title: 'The Crow',
      video: false,
      vote_average: 7.494,
      vote_count: 2802,
    },
    {
      adult: false,
      backdrop_path: '/1YRtgjLb5xxUb2rsNRnr54Oc0B2.jpg',
      genre_ids: [Array],
      id: 10494,
      original_language: 'ja',
      original_title: 'パーフェクトブルー',
      overview:
        "A retired pop singer turned actress' sense of reality is shaken when she is stalked by an obsessed fan and seemingly a ghost of her past.",
      popularity: 19.391,
      poster_path: '/79vujbsWEbX4dzffBV541QXN6sf.jpg',
      release_date: '1997-07-25',
      title: 'Perfect Blue',
      video: false,
      vote_average: 8.272,
      vote_count: 1423,
    },
    {
      adult: false,
      backdrop_path: '/89CkuOoqGuNusIsCzluGADmK72B.jpg',
      genre_ids: [Array],
      id: 10014,
      original_language: 'en',
      original_title: "A Nightmare on Elm Street Part 2: Freddy's Revenge",
      overview:
        "A new family moves into the house on Elm Street, and before long, the kids are again having nightmares about deceased child murderer Freddy Krueger. This time, Freddy attempts to possess a teenage boy to cause havoc in the real world, and can only be overcome if the boy's sweetheart can master her fear.",
      popularity: 32.022,
      poster_path: '/rvAmOv0sZcoQCyJjHPQN4wU8ut4.jpg',
      release_date: '1985-10-31',
      title: "A Nightmare on Elm Street Part 2: Freddy's Revenge",
      video: false,
      vote_average: 5.81,
      vote_count: 1241,
    },
    {
      adult: false,
      backdrop_path: '/g0pF9jXhPqm6TN3AAMWn0YeYayi.jpg',
      genre_ids: [Array],
      id: 9323,
      original_language: 'ja',
      original_title: 'GHOST IN THE SHELL',
      overview:
        "In the year 2029, the barriers of our world have been broken down by the net and by cybernetics, but this brings new vulnerability to humans in the form of brain-hacking. When a highly-wanted hacker known as 'The Puppetmaster' begins involving them in politics, Section 9, a group of cybernetically enhanced cops, are called in to investigate and stop the Puppetmaster.",
      popularity: 46.546,
      poster_path: '/9gC88zYUBARRSThcG93MvW14sqx.jpg',
      release_date: '1995-11-18',
      title: 'Ghost in the Shell',
      video: false,
      vote_average: 7.919,
      vote_count: 2327,
    },
    {
      adult: false,
      backdrop_path: '/ld7UTOGzZSxIMbuYsb6eQ6QdN4h.jpg',
      genre_ids: [Array],
      id: 10096,
      original_language: 'en',
      original_title: '13 Going on 30',
      overview:
        "After total humiliation at her thirteenth birthday party, Jenna Rink wants to just hide until she's thirty. With a little magic, her wish is granted, but it turns out that being thirty isn't as always as awesome as she thought it would be!",
      popularity: 23.6,
      poster_path: '/iNZdSIfhSCMtRILDNyhLn8UKeSG.jpg',
      release_date: '2004-04-13',
      title: '13 Going on 30',
      video: false,
      vote_average: 6.676,
      vote_count: 3985,
    },
    {
      adult: false,
      backdrop_path: '/yNr7tuh3Ka3XLaVniaDmt6wXUho.jpg',
      genre_ids: [Array],
      id: 10719,
      original_language: 'en',
      original_title: 'Elf',
      overview:
        "When young Buddy falls into Santa's gift sack on Christmas Eve, he's transported back to the North Pole and raised as a toy-making elf by Santa's helpers. But as he grows into adulthood, he can't shake the nagging feeling that he doesn't belong. Buddy vows to visit Manhattan and find his real dad, a workaholic publisher.",
      popularity: 14.202,
      poster_path: '/zDHFQmaxlTIJGQDfTrLTL9RK2tQ.jpg',
      release_date: '2003-10-09',
      title: 'Elf',
      video: false,
      vote_average: 6.637,
      vote_count: 2935,
    },
    {
      adult: false,
      backdrop_path: '/2JApfvtgf2snKUtOFn8d1wm5pDU.jpg',
      genre_ids: [Array],
      id: 10796,
      original_language: 'en',
      original_title: 'The One',
      overview:
        "A sheriff's deputy fights an alternate universe version of himself who grows stronger with each alternate self he kills.",
      popularity: 20.703,
      poster_path: '/gcr3t71KmeXINemMrhaGBGVJPwW.jpg',
      release_date: '2001-11-02',
      title: 'The One',
      video: false,
      vote_average: 6.1,
      vote_count: 1146,
    },
    {
      adult: false,
      backdrop_path: '/ejKwHgb6rowGfQtmR6NMqeToFVC.jpg',
      genre_ids: [Array],
      id: 8839,
      original_language: 'en',
      original_title: 'Casper',
      overview:
        'Casper is a kind young ghost who peacefully haunts a mansion in Maine. When specialist James Harvey arrives to communicate with Casper and his fellow spirits, he brings along his teenage daughter, Kat. Casper quickly falls in love with Kat, but their budding relationship is complicated not only by his transparent state, but also by his troublemaking apparition uncles and their mischievous antics.',
      popularity: 39.156,
      poster_path: '/2ah8fNJFZVU3vcXhU5xfAYi2eym.jpg',
      release_date: '1995-05-26',
      title: 'Casper',
      video: false,
      vote_average: 6.311,
      vote_count: 3632,
    },
    {
      adult: false,
      backdrop_path: '/zwJFfKQdfiptK2GY6N8GkZFrAxJ.jpg',
      genre_ids: [Array],
      id: 7340,
      original_language: 'en',
      original_title: 'Carrie',
      overview:
        'Carrie White, a shy and troubled teenage girl who is tormented by her high school peers and her fanatically religious mother, begins to use her powers of telekinesis to exact revenge upon them.',
      popularity: 21.196,
      poster_path: '/uc3OvgmbnYaS5Y0BOjSmC1EmSz1.jpg',
      release_date: '1976-11-03',
      title: 'Carrie',
      video: false,
      vote_average: 7.247,
      vote_count: 2696,
    },
    {
      adult: false,
      backdrop_path: '/9ygcE0Ekc3of7H7HNrB4gMBmOYA.jpg',
      genre_ids: [Array],
      id: 9562,
      original_language: 'en',
      original_title: 'Timeline',
      overview:
        'A group of archaeological students become trapped in the past when they go there to retrieve their professor. The group must survive in 14th century France long enough to be rescued.',
      popularity: 12.551,
      poster_path: '/oZsH2aKqNonBSEGpOTHO2GksSjs.jpg',
      release_date: '2003-11-26',
      title: 'Timeline',
      video: false,
      vote_average: 5.713,
      vote_count: 792,
    },
    {
      adult: false,
      backdrop_path: '/4SxXppJUwjQnd98VLxQEHvH3CfR.jpg',
      genre_ids: [Array],
      id: 9003,
      original_language: 'en',
      original_title: 'Hellraiser',
      overview:
        'An unfaithful wife encounters the zombie of her dead lover while the demonic cenobites are pursuing him after he escaped their sadomasochistic underworld.',
      popularity: 24.174,
      poster_path: '/3Z0oPHyLnk3Vx6ZMC1MiVwIrKhO.jpg',
      release_date: '1987-09-11',
      title: 'Hellraiser',
      video: false,
      vote_average: 6.938,
      vote_count: 1617,
    },
    {
      adult: false,
      backdrop_path: '/aS4H9PxqRAqEW99RR8oILLtxmxg.jpg',
      genre_ids: [Array],
      id: 10330,
      original_language: 'en',
      original_title: 'Freaky Friday',
      overview:
        "Mother and daughter bicker over everything -- what Anna wears, whom she likes and what she wants to do when she's older. In turn, Anna detests Tess's fiancé. When a magical fortune cookie switches their personalities, they each get a peek at how the other person feels, thinks and lives.",
      popularity: 25.841,
      poster_path: '/ipKcZ4Up7dp18XpsfYUc9NKZy3g.jpg',
      release_date: '2003-08-05',
      title: 'Freaky Friday',
      video: false,
      vote_average: 6.355,
      vote_count: 2880,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

export const searchMoviesResults = [
  {
    adult: false,
    backdrop_path: '/czHYg6LQ5926OL8wj5kC09pNR12.jpg',
    genre_ids: [27, 35],
    id: 647302,
    original_language: 'en',
    original_title: 'Benny Loves You',
    overview:
      'Jack, a man desperate to improve his life, throws away his beloved childhood plush, Benny. It’s a move that has disastrous consequences when Benny springs to life with deadly intentions!',
    popularity: 105.201,
    poster_path: '/o32SQgwZQFBa9eK1ADc5Oo1sP4y.jpg',
    release_date: '2019-11-21',
    title: 'Benny Loves You',
    video: false,
    vote_average: 6.4,
    vote_count: 96,
  },
  {
    adult: false,
    backdrop_path: '/7jjwdoIVPJp7gcDo9uE1sVZi2Rs.jpg',
    genre_ids: [18, 10749],
    id: 296096,
    original_language: 'en',
    original_title: 'Me Before You',
    overview:
      'A small town girl is caught between dead-end jobs. A high-profile, successful man becomes wheelchair bound following an accident. The man decides his life is not worth living until the girl is hired for six months to be his new caretaker. Worlds apart and trapped together by circumstance, the two get off to a rocky start. But the girl becomes determined to prove to the man that life is worth living and as they embark on a series of adventures together, each finds their world changing in ways neither of them could begin to imagine.',
    popularity: 82.627,
    poster_path: '/oo2Q3T8juOYFh2G1YJ3oSMAfUyq.jpg',
    release_date: '2016-06-01',
    title: 'Me Before You',
    video: false,
    vote_average: 7.9,
    vote_count: 9373,
  },
  {
    adult: false,
    backdrop_path: '/kkmTDENld0SASZVzqn25mbRYBzU.jpg',
    genre_ids: [53, 9648, 27, 80],
    id: 524251,
    original_language: 'en',
    original_title: 'I See You',
    overview:
      "When a 12-year-old boy goes missing, lead investigator Greg Harper struggles to balance the pressure of the investigation and troubles with his wife, Jackie. Facing a recent affair, great strain is put on the family that slowly gnaws away at Jackie's grip on reality. But after a malicious presence manifests itself in their home and puts their son, Connor, in mortal danger, the cold, hard truth about evil in the Harper household is finally uncovered.",
    popularity: 56.988,
    poster_path: '/E6mwyjpjvQISbUDYCTVg50rJyl.jpg',
    release_date: '2019-09-11',
    title: 'I See You',
    video: false,
    vote_average: 7,
    vote_count: 799,
  },
  {
    adult: false,
    backdrop_path: '/xEY0MV2jSQBz9iOJfCFvLTiPGMA.jpg',
    genre_ids: [53, 80],
    id: 75656,
    original_language: 'en',
    original_title: 'Now You See Me',
    overview:
      'An FBI agent and an Interpol detective track a team of illusionists who pull off bank heists during their performances and reward their audiences with the money.',
    popularity: 50.655,
    poster_path: '/tWsNYbrqy1p1w6K9zRk0mSchztT.jpg',
    release_date: '2013-05-29',
    title: 'Now You See Me',
    video: false,
    vote_average: 7.4,
    vote_count: 13032,
  },
  {
    adult: false,
    backdrop_path: '/q5W3ddBLhocYhMUyvEHHhEryfVP.jpg',
    genre_ids: [18, 35],
    id: 405177,
    original_language: 'en',
    original_title: "Where'd You Go, Bernadette",
    overview:
      "When architect-turned-recluse Bernadette Fox goes missing prior to a family trip to Antarctica, her 15-year-old daughter Bee goes on a quest with Bernadette's husband to find her.",
    popularity: 35.779,
    poster_path: '/BziuuZULnGmTRLthEty1QdKSEo.jpg',
    release_date: '2019-08-16',
    title: "Where'd You Go, Bernadette",
    video: false,
    vote_average: 6.7,
    vote_count: 454,
  },
  {
    adult: false,
    backdrop_path: '/mTrJTowSPK8DmSyo270GJ2HNvbc.jpg',
    genre_ids: [18, 10749],
    id: 6023,
    original_language: 'en',
    original_title: 'P.S. I Love You',
    overview:
      'A young widow discovers that her late husband has left her 10 messages intended to help ease her pain and start a new life.',
    popularity: 23.31,
    poster_path: '/nuOGIDqDFaX20i4Zfi5VN47lqXh.jpg',
    release_date: '2007-11-15',
    title: 'P.S. I Love You',
    video: false,
    vote_average: 7.2,
    vote_count: 2767,
  },
  {
    adult: false,
    backdrop_path: '/1sWDuBwQcETRrgSV7V16qtqFfnB.jpg',
    genre_ids: [53, 28, 35],
    id: 291805,
    original_language: 'en',
    original_title: 'Now You See Me 2',
    overview:
      'One year after outwitting the FBI and winning the public’s adulation with their mind-bending spectacles, the Four Horsemen resurface only to find themselves face to face with a new enemy who enlists them to pull off their most dangerous heist yet.',
    popularity: 43.124,
    poster_path: '/A81kDB6a1K86YLlcOtZB27jriJh.jpg',
    release_date: '2016-06-02',
    title: 'Now You See Me 2',
    video: false,
    vote_average: 6.8,
    vote_count: 8996,
  },
  {
    adult: false,
    backdrop_path: '/i60mGxEh6NT8qcR1sHDefmSTSCT.jpg',
    genre_ids: [35, 18, 10749],
    id: 450489,
    original_language: 'en',
    original_title: 'Irreplaceable You',
    overview:
      'A couple who have known each other since 8 are destined to be together until death do them apart.',
    popularity: 14.537,
    poster_path: '/hkflwtWCJffdDSwg63fdDFbwOvS.jpg',
    release_date: '2018-02-16',
    title: 'Irreplaceable You',
    video: false,
    vote_average: 7,
    vote_count: 599,
  },
  {
    adult: false,
    backdrop_path: '/9AvYdiDWutgsy67klIMVXImmv2G.jpg',
    genre_ids: [10749, 35],
    id: 537739,
    original_language: 'en',
    original_title: 'Can You Keep a Secret?',
    overview:
      'Emma Corrigan, a girl with a few secrets on a turbulent plane ride, thinks she’s about to die, Emma spills them all to the handsome stranger sitting next to her. At least, she thought he was a stranger. But then, her company’s young and elusive CEO, arrives at the office. It’s him. And he knows every single humiliating detail about Emma.',
    popularity: 43.654,
    poster_path: '/7QtCOlHESPEYtFANmd4yLqsYKZ4.jpg',
    release_date: '2019-09-13',
    title: 'Can You Keep a Secret?',
    video: false,
    vote_average: 6.6,
    vote_count: 643,
  },
  {
    adult: false,
    backdrop_path: '/ycGFcMLv6xlj0EzxKhbZHhXT1vb.jpg',
    genre_ids: [14, 18],
    id: 309425,
    original_language: 'en',
    original_title: 'Do You Believe?',
    overview:
      'When a pastor is shaken by the visible faith of a street-corner preacher, he is reminded that true belief always requires action. His response ignites a journey that impacts everyone it touches in ways that only God could orchestrate.',
    popularity: 21.769,
    poster_path: '/89fJ4hV9fCB01EvhhLOgjMJI4A6.jpg',
    release_date: '2015-03-20',
    title: 'Do You Believe?',
    video: false,
    vote_average: 6.6,
    vote_count: 98,
  },
  {
    adult: false,
    backdrop_path: '/cpZAXIYA0lkZMpAt7d1MmH8ojNV.jpg',
    genre_ids: [28, 53, 12],
    id: 667,
    original_language: 'en',
    original_title: 'You Only Live Twice',
    overview:
      'A mysterious spacecraft captures Russian and American space capsules and brings the two superpowers to the brink of war. James Bond investigates the case in Japan and comes face to face with his archenemy Blofeld.',
    popularity: 26.614,
    poster_path: '/dbhveh4EKTM64nRJiPz3ssNrao4.jpg',
    release_date: '1967-06-13',
    title: 'You Only Live Twice',
    video: false,
    vote_average: 6.6,
    vote_count: 1474,
  },
  {
    adult: false,
    backdrop_path: '/chAGSv4DB9s3fsgULpSZQLN7LgN.jpg',
    genre_ids: [27, 9648, 18, 53],
    id: 514593,
    original_language: 'en',
    original_title: 'You Should Have Left',
    overview:
      'In an effort to repair their relationship, a couple books a vacation in the countryside for themselves and their daughter. What starts as a perfect retreat begins to fall apart as one loses their grip on reality, and a sinister force tries to tear them apart.',
    popularity: 28.837,
    poster_path: '/tpOwE6xsWnu4lKeKbKW0R3iClM.jpg',
    release_date: '2020-06-18',
    title: 'You Should Have Left',
    video: false,
    vote_average: 5.9,
    vote_count: 390,
  },
  {
    adult: false,
    backdrop_path: '/nWvetzjKuig2D3ZAzt6UQGy4hNL.jpg',
    genre_ids: [35, 10749],
    id: 38303,
    original_language: 'en',
    original_title: 'You Again',
    overview:
      "History -- make that high school -- may repeat itself when Marni learns that Joanna, the mean girl from her past, is set to be her sister-in-law. Before the wedding bells toll, Marni must show her brother that a tiger doesn't change its stripes. On Marni's side is her mother, while Joanna's backed by her wealthy aunt.",
    popularity: 14.017,
    poster_path: '/9qI5JE6yjmtakTankuDOMZ1vgEx.jpg',
    release_date: '2010-09-24',
    title: 'You Again',
    video: false,
    vote_average: 6.3,
    vote_count: 1027,
  },
  {
    adult: false,
    backdrop_path: '/qhvwNJnnjFgMaGOiO14ODByl5Ad.jpg',
    genre_ids: [53, 10749, 18],
    id: 412105,
    original_language: 'en',
    original_title: 'You Get Me',
    overview:
      'After arguing with his girlfriend, Ali, Tyler lands in the arms of sexy new girl, Holly. The next morning, he finds that not only does Ali agree to take him back, but Holly is a new student at their school and is dead set on her new man.',
    popularity: 16.59,
    poster_path: '/5eV0mIQqSztD3McjO22EOFlQDj1.jpg',
    release_date: '2017-06-19',
    title: 'You Get Me',
    video: false,
    vote_average: 5.6,
    vote_count: 1520,
  },
  {
    adult: false,
    backdrop_path: '/iACkB2Xddzhqi7YWR1IjIOhqCVW.jpg',
    genre_ids: [35, 10749],
    id: 12658,
    original_language: 'en',
    original_title: 'Someone Like You...',
    overview:
      "Jane Goodale has everything going for her. She's a producer on a popular daytime talk show, and is in a hot romance with the show's dashing executive producer Ray. But when the relationship goes terribly awry, Jane begins an extensive study of the male animal, including her womanizing roommate Eddie. Jane puts her studies and romantic misadventure to use as a pseudonymous sex columnist -- and becomes a sensation.",
    popularity: 10.921,
    poster_path: '/j6lr8jE8hDgx75GeRRL1greDmkz.jpg',
    release_date: '2001-03-30',
    title: 'Someone Like You...',
    video: false,
    vote_average: 6,
    vote_count: 274,
  },
  {
    adult: false,
    backdrop_path: '/yYQGucYHplegjvDqpzOiEkQFevR.jpg',
    genre_ids: [18, 35, 10749],
    id: 1544,
    original_language: 'en',
    original_title: 'Imagine Me & You',
    overview:
      'During her wedding ceremony, Rachel notices Luce in the audience and feels instantly drawn to her. The two women become close friends, and when Rachel learns that Luce is a lesbian, she realizes that despite her happy marriage to Heck, she is falling for Luce. As she questions her sexual orientation, Rachel must decide between her stable relationship with Heck and her exhilarating new romance with Luce.',
    popularity: 13.69,
    poster_path: '/a7CbxY3TMwFKX6awlBxhb7Es6tS.jpg',
    release_date: '2005-02-01',
    title: 'Imagine Me & You',
    video: false,
    vote_average: 7.6,
    vote_count: 724,
  },
  {
    adult: false,
    backdrop_path: '/rwcEaZghpbt6mV0lRQ9ymz5oM9B.jpg',
    genre_ids: [18, 80],
    id: 640,
    original_language: 'en',
    original_title: 'Catch Me If You Can',
    overview:
      'A true story about Frank Abagnale Jr. who, before his 19th birthday, successfully conned millions of dollars worth of checks as a Pan Am pilot, doctor, and legal prosecutor. An FBI agent makes it his mission to put him behind bars. But Frank not only eludes capture, he revels in the pursuit.',
    popularity: 30.755,
    poster_path: '/ctjEj2xM32OvBXCq8zAdK3ZrsAj.jpg',
    release_date: '2002-12-25',
    title: 'Catch Me If You Can',
    video: false,
    vote_average: 7.9,
    vote_count: 11501,
  },
  {
    adult: false,
    backdrop_path: '/fGJSNmTJVOIvv0JmOp2ojSOP87P.jpg',
    genre_ids: [10749, 18],
    id: 310888,
    original_language: 'en',
    original_title: 'Southside with You',
    overview:
      "Chronicles a single day in the summer of 1989 when the future president of the United States, Barack Obama, wooed his future First Lady on an epic first date across Chicago's South Side.",
    popularity: 15.452,
    poster_path: '/4ktA7D8Xgxw4QkWNSvRgEedHWn5.jpg',
    release_date: '2016-08-26',
    title: 'Southside with You',
    video: false,
    vote_average: 5.6,
    vote_count: 171,
  },
  {
    adult: false,
    backdrop_path: '/wuqQ2NJ35rynxcT01AWHX5VeRdF.jpg',
    genre_ids: [35, 18],
    id: 375785,
    original_language: 'en',
    original_title: 'Then Came You',
    overview:
      'An American hypochondriac who is working as a baggage handler is forced to confront his fears when a British teenager with a terminal illness enlists him to help her carry out her eccentric bucket list.',
    popularity: 16.208,
    poster_path: '/9hIA3dgyOWj1MLXYrJ7SZ6lckM9.jpg',
    release_date: '2019-02-01',
    title: 'Then Came You',
    video: false,
    vote_average: 7.6,
    vote_count: 344,
  },
  {
    adult: false,
    backdrop_path: '/9LsJP9OuIBmBUxZpmVKtUUjF0PA.jpg',
    genre_ids: [10749, 35],
    id: 565426,
    original_language: 'en',
    original_title: 'To All the Boys: P.S. I Still Love You',
    overview:
      'Lara Jean and Peter have just taken their romance from pretend to officially real when another recipient of one of her love letters enters the picture.',
    popularity: 64.245,
    poster_path: '/maib5VlmEqp5xlN8lptnBSftp2o.jpg',
    release_date: '2020-02-12',
    title: 'To All the Boys: P.S. I Still Love You',
    video: false,
    vote_average: 6.9,
    vote_count: 2048,
  },
];
